# IMPORTANT: Changes to this file will be applied to all environments, even if you deploy dev only.

---
apiVersion: meta.p6m.dev/v1alpha1
kind: PlatformApplication
metadata:
  name: fe-{{package-name}}
  labels:
    p6m.dev/domain: company
    p6m.dev/app: fe-{{package-name}}
    p6m.dev/project-domain: {{org-prefix}}-{{package-name}}
    p6m.dev/project-name: {{org-prefix}}-{{package-name}}-{{package-name}}
spec:
  autoscaling:
    enabled: true
  deployment:
    image: fe-{{package-name}}-server:latest # Set to a digest in the .platform repo patch
    ports:
      - protocol: http
        port: 3000
    readinessProbe:
      port: 3000
      path: /api/health
  networking:
    ingress:
      enabled: true
      oidc: false
      path: /
      hostnames: [] # This is set in the patch files per environment
      cdn:
        enabled: true
        required: true
        wafId: null # This is set in the patch files per environment
        domains: [] # This is set in the patch files per environment
  secrets:
    - name: {{package-name}}-secret
