---
apiVersion: meta.p6m.dev/v1alpha1
kind: PlatformApplication
metadata:
  name: {{package-name}}
spec:
  config:
    REACT_APP_ENV: prod
  networking:
    ingress:
      hostnames:
        - {{package-name}}.eks.us-east-2.aws.prd.{{org-prefix}}-{{org-suffix}}.p6m.run
      cdn:
        domains:
          - {{package-name}}.cdn.aws.prd.{{org-prefix}}-{{org-suffix}}.p6m.run